import { useState, useEffect } from 'react';

export default function KeyGen() {
  const [keys, setKeys] = useState({ publicKey: '', privateKey: '' });
  const [status, setStatus] = useState('Waiting for C-WASM...');
  const [wasmReady, setWasmReady] = useState(false);

  // 1. LOAD THE COMPILED C CODE
  // Loaded manually (not via next/script) and idempotently: on re-visits the
  // script tag and the initialized Emscripten runtime are reused.
  useEffect(() => {
    let cancelled = false;

    const markReady = () => {
      if (cancelled) return;
      setWasmReady(true);
      setStatus('Ready. Loaded keygen.c via WebAssembly!');
    };

    const watchRuntime = () => {
      if (window.Module?.calledRun) {
        markReady(); // Runtime already initialized
      } else {
        window.Module.onRuntimeInitialized = markReady;
      }
    };

    if (document.querySelector('script[src="/wasm_keygen.js"]')) {
      watchRuntime();
    } else {
      const script = document.createElement('script');
      script.src = '/wasm_keygen.js';
      script.onload = watchRuntime;
      script.onerror = () => {
        if (!cancelled) setStatus('Error: failed to load wasm_keygen.js');
      };
      document.body.appendChild(script);
    }

    return () => { cancelled = true; };
  }, []);

  // Helper: Convert C-memory (Uint8Array) to Hex String
  const toHex = (arr) =>
    Array.from(arr).map(b => b.toString(16).padStart(2, '0')).join('').toUpperCase();

  return (
    <div className="p-8 font-sans max-w-4xl mx-auto">
      <h1 className="text-2xl font-bold mb-6 text-green-700">PQC Key Generator (C + WASM)</h1>
      <p className="mb-6 text-gray-600">
        This page runs your <b>C code</b> directly in the browser using WebAssembly.
      </p>

      <button 
        disabled={!wasmReady}
        onClick={() => {
          try {
            const Module = window.Module;
            setStatus('Allocating memory in C...');

            // A. Get sizes from C
            const pkSize = Module._get_pubkey_size(); // 800
            const skSize = Module._get_privkey_size(); // 1632

            // B. Allocate memory in the WASM Heap
            const pkPtr = Module._malloc(pkSize);
            const skPtr = Module._malloc(skSize);

            // C. Run the C function!
            Module._generate_kyber_keys(pkPtr, skPtr);

            // D. Copy results out of WASM memory
            const pkBytes = Module.HEAPU8.slice(pkPtr, pkPtr + pkSize);
            const skBytes = Module.HEAPU8.slice(skPtr, skPtr + skSize);

            // E. Display them
            setKeys({
              publicKey: toHex(pkBytes),
              privateKey: toHex(skBytes)
            });

            // F. Wipe the private key from the WASM heap, then free
            Module.HEAPU8.fill(0, skPtr, skPtr + skSize);
            Module._free(pkPtr);
            Module._free(skPtr);

            setStatus('Success! Keys generated by liboqs (C).');
          } catch (e) {
            setStatus('Error: ' + e.message);
          }
        }}
        className={`px-6 py-2 rounded font-bold mb-6 text-white ${wasmReady ? 'bg-green-600 hover:bg-green-700' : 'bg-gray-400'}`}
      >
        {wasmReady ? "Generate Keys (Run C Code)" : "Loading WASM..."}
      </button>

      <p className="font-bold mb-4">{status}</p>

      <div className="space-y-6">
        <div>
          <h3 className="font-bold text-lg">Public Key</h3>
          <textarea className="w-full h-32 p-2 border text-xs font-mono" readOnly value={keys.publicKey} />
        </div>

        <div>
          <h3 className="font-bold text-lg text-red-600">Private Key</h3>
          <textarea className="w-full h-32 p-2 border text-xs font-mono" readOnly value={keys.privateKey} />
        </div>
      </div>
    </div>
  );
}